from bastet.cli.app import app
from bastet.core.secrets.notes import SecretNote, SecretPath
from conftest import git


def test_add_role_to_host_writes_file_and_section(runner, inventory):
    result = runner.invoke(app, ["add", "role", "packages", "pve1", "-y"])
    assert result.exit_code == 0, result.output
    text = (inventory / "_roles" / "hosts" / "pve1" / "packages.md").read_text()
    assert text.startswith('---\nbastet: role\nrole: packages\napplies_to: "[[pve1]]"\n---\n')
    assert "![[roles-here.base]]" in (inventory / "hosts" / "pve1.md").read_text()
    again = runner.invoke(app, ["add", "role", "packages", "pve1", "-y"])
    assert again.exit_code != 0 and "already exists" in again.output


def test_add_role_to_lab_and_unknown(runner, inventory):
    assert runner.invoke(app, ["add", "role", "systemd", "lab", "-y"]).exit_code == 0
    assert 'applies_to: "[[Homelab]]"' in (inventory / "_roles" / "lab" / "systemd.md").read_text()
    bad = runner.invoke(app, ["add", "role", "nope", "pve1", "-y"])
    assert bad.exit_code != 0 and "unknown role" in bad.output


def test_add_role_offers_roles_and_targets(runner, inventory):
    """Lists `lab`, then the generated type and OS groups (automatic), before the user's own groups."""
    groups = inventory / "_bastet" / "groups"
    groups.mkdir(parents=True)
    (groups / "proxmox.md").write_text(
        "---\nbastet: group\ngenerated: true\nmatch:\n  type: proxmox\n---\nEvery proxmox host. Generated by Bastet.\n")
    (groups / "debian.md").write_text(
        "---\nbastet: group\ngenerated: true\nmatch:\n  os: debian\n---\nEvery host whose OS is debian.\n")
    git(inventory, "add", ".")
    git(inventory, "commit", "-q", "-m", "groups")
    result = runner.invoke(app, ["add", "role"], input="base\nproxmox\ny\n")
    assert result.exit_code == 0, result.output
    assert "Roles:" in result.output and "Add to:" in result.output and "every host" in result.output
    assert "every proxmox host" in result.output and "every debian host" in result.output
    assert (inventory / "_roles" / "groups" / "proxmox" / "base.md").exists()


def test_add_role_asks_to_set_needed_secrets(runner, secret_keys, inventory, test_role):
    result = runner.invoke(app, ["add", "role", "impliedsecret", "box"], input="y\ny\ns\n")
    assert result.exit_code == 0, result.output
    assert "Set them now?" in result.output
    assert "bastet secret set box impliedsecret api_key" in result.output
    assert not (inventory / "_secrets" / "box" / "impliedsecret" / "api_key.md").exists()
